// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// this is a firebase configuration file
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDYlknY618fPhSUytCbvDvVogPaM6OLY8',
    appId: '1:375759341222:web:ec7d5089698f21d22fd667',
    messagingSenderId: '375759341222',
    projectId: 'finwise-1dbcd',
    authDomain: 'finwise-1dbcd.firebaseapp.com',
    storageBucket: 'finwise-1dbcd.firebasestorage.app',
    measurementId: 'G-MWFK2093N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDij-WswHP5qis-li-xbuCBdomDIkpB1gk',
    appId: '1:375759341222:android:81cc4f51a88f938c2fd667',
    messagingSenderId: '375759341222',
    projectId: 'finwise-1dbcd',
    storageBucket: 'finwise-1dbcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZS2xteisDfgaw0GwZ_x-IYwDQ9BQTcmA',
    appId: '1:375759341222:ios:09f9290f63b5cbd92fd667',
    messagingSenderId: '375759341222',
    projectId: 'finwise-1dbcd',
    storageBucket: 'finwise-1dbcd.firebasestorage.app',
    iosBundleId: 'com.example.finwiseApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZS2xteisDfgaw0GwZ_x-IYwDQ9BQTcmA',
    appId: '1:375759341222:ios:09f9290f63b5cbd92fd667',
    messagingSenderId: '375759341222',
    projectId: 'finwise-1dbcd',
    storageBucket: 'finwise-1dbcd.firebasestorage.app',
    iosBundleId: 'com.example.finwiseApplication',
  );
}
